### ISSUE TITLE
Launching an editor makes the SBT hang

### ISSUE THREAD

**Issue by patrick-bohan** [agemooij/sbt-prompt#7]
If you do something like "git commit" and git brings up an editor (in my case vim), the editor does not display and there's no obvious way of exiting except CTRL-C which kills SBT too.

**Comment by agemooij** [comment]
I'm not sure I understand what you mean and how it relates to the sbt-prompt plugin. "git commit" is not part of the functionality of sbt-prompt, although you might be talking about the embedded [sbt-git](https://github.com/sbt/sbt-git) plugin, which does allow you to interact with Git from the sbt shell. Any issues you have with its functionality should be posted on their own site since sbt-prompt just uses it to get the current git branch to display.

I'm working on a new version of sbt-git that upgrades the dependency on the sbt-git plugin to their latest version, which might include some bug fixes. If you want the latest version of sbt-git, you can simply override the version embedded in sbt-ptompt by adding that latest version to your plugins.sbt. Sbt (and sbt-prompt) will then automatically use that latest version.

If you mean something else, could you please try to explain with a little more detail?

Hope this helps,
Age

**Comment by patrick-bohan** [comment]
Hmm, I agree this is probably part of sbt-git. I didn't start using the git commands until after I installed sbt-prompt, so I think I made a false connection.

**Comment by agemooij** [comment]
No worries. Try using the latest version of sbt-git, it might already solve your problem.
